export const FILTRAR_POKEMON_TIPO = 'FILTRAR_POKEMON_TIPO';
export const OBTENER_DATA_POKEMON = 'OBTENER_DATA_POKEMON';
export const OBTENER_DATA_POKEMON_ID = 'OBTENER_DATA_POKEMON_ID';
export const OBTENER_DATA_PRINCIPAL_POKEMON_ID = 'OBTENER_DATA_PRINCIPAL_POKEMON_ID';
export const EXISTE_POKEMON_INPUT = 'EXISTE_POKEMON_INPUT';

